import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { appPath } from './paths.js';

test('a visitor can try the demo without registering', async ({ page }) => {
  await page.goto(appPath('/'));
  await page.getByRole('link', { name: 'Try demo' }).click();
  await expect(page.getByText('Read-only demo')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Cedar House' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add installation' })).toHaveCount(0);
});

test('registration, persistent login, site CRUD, logout and login', async ({ page, context, baseURL }) => {
  const email = `browser-${randomUUID()}@example.test`;
  const password = randomUUID() + randomUUID();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(appPath('/register'));
  await page.getByLabel('Name', { exact: true }).fill('Portfolio Tester');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My installations' })).toBeVisible();
  const sessionCookie = (await context.cookies()).find((cookie) => cookie.name.endsWith('sm_session'));
  expect(sessionCookie?.httpOnly).toBe(true);
  expect(sessionCookie?.sameSite).toBe('Lax');
  expect(sessionCookie?.secure).toBe(Boolean(baseURL?.startsWith('https:')));
  await expect(page.getByText('No installations yet.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Add installation' }).click();
  await page.getByLabel('Installation name').fill('Test rooftop');
  await page.getByLabel('Location').fill('Austin, TX');
  await page.getByLabel('Installed capacity (kW)').fill('7.125');
  await page.getByRole('button', { name: 'Save installation' }).click();
  await expect(page.getByRole('heading', { name: 'Test rooftop' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Test rooftop' })).toBeVisible();
  await page.getByRole('link', { name: 'Monitor', exact: true }).click();
  await expect(page.getByText('No readings in this date range.')).toBeVisible();
  await page.getByRole('button', { name: 'Add reading' }).click();
  await page.getByLabel('Solar power (kW)').fill('0');
  await page.getByLabel('Inverter temperature (°C, optional)').fill('50');
  await page.getByRole('button', { name: 'Save reading' }).click();
  await expect(page.locator('.metric-card').first()).toContainText('0 kW');
  await expect(page.getByText('Inverter temperature reached 50 °C')).toBeVisible();
  await page.getByRole('button', { name: 'Resolve', exact: true }).click();
  await expect(page.locator('.alert-list')).toContainText('Resolved');
  await page.getByRole('link', { name: '← Installations' }).click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Installation name').fill('Updated rooftop');
  await page.getByRole('button', { name: 'Save installation' }).click();
  await expect(page.getByRole('heading', { name: 'Updated rooftop' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.getByRole('button', { name: 'Log out' }).click();
  await expect(page).toHaveURL(appPath('/login'));
  await page.goto(appPath('/sites'));
  await expect(page).toHaveURL(appPath('/login'));
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Updated rooftop' })).toBeVisible();
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.getByText('No installations yet.', { exact: false })).toBeVisible();
});
